### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by ralfebert** [remuslazar/osx-xliff-tool#3]
Are there any plans to make the code available under an open source license so that its possible to contribute to the project?
(thanks for making a nice and free XLIFF editor!)

**Comment by svenfre** [comment]
That would be cool, I'd love to contribute :)

**Comment by remuslazar** [comment]
@ralfebert, @svenfre unfortunately, because of time constraints I don't have the resources to maintain this tool as an open source collaborative project. Please don't get me wrong here, I like open source and this was the reason why I made the source code publicly available.

I am still devoted to it and I will release a new version very soon, addressing some of the bugs and feature requests.
