### ISSUE TITLE
"\n" issue. 

### ISSUE THREAD

**Issue by eikebartels** [remuslazar/osx-xliff-tool#5]
When I add "\n" the .string file breaks

**Comment by remuslazar** [comment]
@eikebartels Xcode replaces (while using the "Editor > Export for Localization" Feature) all the `\n` from all string literals in the source code with a regular CR utf8 char in the `<source>` tag, so just use option+enter to enter a "new line" in the target table cell input field, this should work just fine.

**Comment by Idomo** [comment]
> @eikebartels Xcode replaces (while using the "Editor > Export for Localization" Feature) all the `\n` from all string literals in the source code with a regular CR utf8 char in the `<source>` tag, so just use option+enter to enter a "new line" in the target table cell input field, this should work just fine.

option+enter works only when you're translating text from `Storyboard`, if you'll create some `NSLocalizedString()` and try to translate it with `\n` or option+enter you'll get error in xCode that you have missing translation in your project/import.

Maybe it's only since the new xCode versions so the app isn't updated to solve this yet.
Please try to make some time and fix this, this is the beast `xliff` tool by far and it's very disappoints that it won't let me create strings with `line breaks`. 

Thanks,
Ido.
